export const LIST_PRODUCTS = 'LIST_PRODUCTS';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const CLEAR_SELECTED_PRODUCT = 'CLEAR_SELECTED_PRODUCT';
export const CHANGE_FILTER = 'CHANGE_FILTER';
